
POST http://localhost:8000/funql HTTP/1.1
content-type: application/json
token:eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NDAyNDQxODEuMDIzLCJ1c2Vyc0lkIjoiNjBkMWNkYTI3OGUzZjkwNTU4OTRlMDI3In0.t0JqV-lflf99RYgEEVy2m_MmW_k8XLSr6jQZpeUMmZbjmS4tZA4-GJYimF0z_8KUr_EoKQABzTaX6RV-3IrSDQ

{
    "contents":"dynamic",
    "details":{
        "set":{
		"title": "mohammad",
		"summary": "testing isdb",
		"content": "string",
		"blogCategoryID": "60cf59ae47eddd3cf9c5b4c3",
		"photo":"11113131",
        "blogTagIDs":["60cf59ae47eddd3cf9c5b4ea"]
        },
        "get":{
            # "title":1,
            # "blogCategory":{
            #     "name":1
            # },
            # "author":{
            #     "name":1
            # }
        }
    },
    "wants":{
        "model":"BlogPost",
        "doit":"createBlogPost"
    }
}
